[build]
  command = "hugo --gc --minify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.161.1"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Functions 配置
[functions]
  node_bundler = "esbuild"
